-- Generated by tools/build_species.py from PokéAPI. Do not edit by hand;
-- rerun the tool instead.
-- Evolutions from FireRed's own species into #387-1025.
return {
  { method = "EVO_ITEM", item = "thunder-stone", target = 462, source = 82 },
  { method = "EVO_TRADE_ITEM", item = "protector", target = 464, source = 112 },
  { method = "EVO_ITEM", item = "black-augurite", target = 900, source = 123 },
  { method = "EVO_TRADE_ITEM", item = "electirizer", target = 466, source = 125 },
  { method = "EVO_TRADE_ITEM", item = "magmarizer", target = 467, source = 126 },
  { method = "EVO_ITEM", item = "shiny-stone", target = 468, source = 176 },
  { method = "EVO_ITEM", item = "dusk-stone", target = 430, source = 198 },
  { method = "EVO_ITEM", item = "dusk-stone", target = 429, source = 200 },
  { method = "EVO_ITEM", item = "peat-block", target = 901, source = 217 },
  { method = "EVO_TRADE_ITEM", item = "dubious-disc", target = 474, source = 233 },
  { method = "EVO_ITEM", item = "dawn-stone", target = 475, source = 281 },
  { method = "EVO_ITEM", item = "thunder-stone", target = 476, source = 299 },
  { method = "EVO_ITEM", item = "shiny-stone", target = 407, source = 315 },
  { method = "EVO_TRADE_ITEM", item = "reaper-cloth", target = 477, source = 356 },
  { method = "EVO_ITEM", item = "dawn-stone", target = 478, source = 361 },
}
