-- Generated by tools/build_species.py from PokéAPI. Do not edit by hand;
-- rerun the tool instead.
return { version = 1, count = 639, shards = { "001.lua", "002.lua", "003.lua", "004.lua", "005.lua", "006.lua", "007.lua", "008.lua" } }
