-- Generated by tools/build_items.py. Do not edit by hand; rerun the
-- tool instead (see tools/build_items.py's ORDER for why entries are
-- append-only).
--
-- The evolution items no Gen 3 game has, that this mod's own evolutions
-- (data/species, data/species/crossgen.lua) call for. src/items.lua
-- registers each at its own fixed slot (index = 900 + position here).
return {
  { slug = "dawn-stone", id = "DAWN_STONE", name = "Dawn Stone", index = 900 },
  { slug = "dubious-disc", id = "DUBIOUS_DISC", name = "Dubious Disc", index = 901 },
  { slug = "dusk-stone", id = "DUSK_STONE", name = "Dusk Stone", index = 902 },
  { slug = "electirizer", id = "ELECTIRIZER", name = "Electirizer", index = 903 },
  { slug = "ice-stone", id = "ICE_STONE", name = "Ice Stone", index = 904 },
  { slug = "magmarizer", id = "MAGMARIZER", name = "Magmarizer", index = 905 },
  { slug = "protector", id = "PROTECTOR", name = "Protector", index = 906 },
  { slug = "reaper-cloth", id = "REAPER_CLOTH", name = "Reaper Cloth", index = 907 },
  { slug = "sachet", id = "SACHET", name = "Sachet", index = 908 },
  { slug = "shiny-stone", id = "SHINY_STONE", name = "Shiny Stone", index = 909 },
  { slug = "sweet-apple", id = "SWEET_APPLE", name = "Sweet Apple", index = 910 },
  { slug = "tart-apple", id = "TART_APPLE", name = "Tart Apple", index = 911 },
  { slug = "whipped-dream", id = "WHIPPED_DREAM", name = "Whipped Dream", index = 912 },
  { slug = "auspicious-armor", id = "AUSPICIOUS_ARMOR", name = "Auspicious Armor", index = 913 },
  { slug = "black-augurite", id = "BLACK_AUGURITE", name = "Black Augurite", index = 914 },
  { slug = "malicious-armor", id = "MALICIOUS_ARMOR", name = "Malicious Armor", index = 915 },
  { slug = "metal-alloy", id = "METAL_ALLOY", name = "Metal Alloy", index = 916 },
  { slug = "peat-block", id = "PEAT_BLOCK", name = "Peat Block", index = 917 },
  { slug = "syrupy-apple", id = "SYRUPY_APPLE", name = "Syrupy Apple", index = 918 },
}
