-- Generated by tools/build_items.py. Do not edit by hand; rerun the tool
-- instead. index -> where its 24x24 icon sits in assets/items/icons.png,
-- for whichever of this mod's items the icon pack had art for.
return {
  size = 24,
  cells = {
    [900] = { x = 0, y = 0 }, -- dawn-stone
    [901] = { x = 24, y = 0 }, -- dubious-disc
    [902] = { x = 48, y = 0 }, -- dusk-stone
    [903] = { x = 72, y = 0 }, -- electirizer
    [904] = { x = 96, y = 0 }, -- ice-stone
    [905] = { x = 120, y = 0 }, -- magmarizer
    [906] = { x = 144, y = 0 }, -- protector
    [907] = { x = 168, y = 0 }, -- reaper-cloth
    [908] = { x = 192, y = 0 }, -- sachet
    [909] = { x = 216, y = 0 }, -- shiny-stone
    [910] = { x = 240, y = 0 }, -- sweet-apple
    [911] = { x = 264, y = 0 }, -- tart-apple
    [912] = { x = 288, y = 0 }, -- whipped-dream
    [913] = { x = 312, y = 0 }, -- auspicious-armor
    [914] = { x = 336, y = 0 }, -- black-augurite
    [915] = { x = 360, y = 0 }, -- malicious-armor
    [916] = { x = 0, y = 24 }, -- metal-alloy
    [917] = { x = 24, y = 24 }, -- peat-block
    [918] = { x = 48, y = 24 }, -- syrupy-apple
    [919] = { x = 72, y = 24 }, -- cracked-pot
    [920] = { x = 96, y = 24 }, -- chipped-pot
    [921] = { x = 120, y = 24 }, -- unremarkable-teacup
    [922] = { x = 144, y = 24 }, -- masterpiece-teacup
    [923] = { x = 168, y = 24 }, -- strawberry-sweet
    [924] = { x = 192, y = 24 }, -- berry-sweet
    [925] = { x = 216, y = 24 }, -- love-sweet
    [926] = { x = 240, y = 24 }, -- star-sweet
    [927] = { x = 264, y = 24 }, -- clover-sweet
    [928] = { x = 288, y = 24 }, -- flower-sweet
    [929] = { x = 312, y = 24 }, -- ribbon-sweet
  },
}
