"""
PokéAPI ability -> the Gen 3 ability this mod gives instead.

The Gen 3 battle engine implements abilities as hard-coded name checks over
the cart's own ids (1-77); a mod cannot add an ability, only point a species
at one that exists (src/core/game3/battle/abilities.lua, adapter.lua
ABILITY_BY_ID). So every newer ability is mapped to the closest cart ability.
The species then shows that ability's name and behaves like it.

Ids are the CART's, not PokéAPI's: PokéAPI 1-75 are the same ability in the
same place; PokéAPI 76 is Air Lock but the cart's 76 is Cacophony (unused) and
Air Lock is 77.

CLOSEST is keyed by PokéAPI slug. Each value is (cart id, reason).
"""

from __future__ import annotations

# cart ability ids this table points at (names from the cart's ability_names)
STENCH, DRIZZLE, SPEED_BOOST, BATTLE_ARMOR, STURDY, DAMP, LIMBER = 1, 2, 3, 4, 5, 6, 7
SAND_VEIL, STATIC, VOLT_ABSORB, WATER_ABSORB, OBLIVIOUS, CLOUD_NINE = 8, 9, 10, 11, 12, 13
COMPOUND_EYES, INSOMNIA, COLOR_CHANGE, IMMUNITY, FLASH_FIRE, SHIELD_DUST = 14, 15, 16, 17, 18, 19
OWN_TEMPO, SUCTION_CUPS, INTIMIDATE, SHADOW_TAG, ROUGH_SKIN, WONDER_GUARD = 20, 21, 22, 23, 24, 25
LEVITATE, EFFECT_SPORE, SYNCHRONIZE, CLEAR_BODY, NATURAL_CURE, LIGHTNING_ROD = 26, 27, 28, 29, 30, 31
SERENE_GRACE, SWIFT_SWIM, CHLOROPHYLL, ILLUMINATE, TRACE, HUGE_POWER = 32, 33, 34, 35, 36, 37
POISON_POINT, INNER_FOCUS, MAGMA_ARMOR, WATER_VEIL, MAGNET_PULL, SOUNDPROOF = 38, 39, 40, 41, 42, 43
RAIN_DISH, SAND_STREAM, PRESSURE, THICK_FAT, EARLY_BIRD, FLAME_BODY = 44, 45, 46, 47, 48, 49
RUN_AWAY, KEEN_EYE, HYPER_CUTTER, PICKUP, TRUANT, HUSTLE = 50, 51, 52, 53, 54, 55
CUTE_CHARM, PLUS, MINUS, FORECAST, STICKY_HOLD, SHED_SKIN = 56, 57, 58, 59, 60, 61
GUTS, MARVEL_SCALE, LIQUID_OOZE, OVERGROW, BLAZE, TORRENT = 62, 63, 64, 65, 66, 67
SWARM, ROCK_HEAD, DROUGHT, ARENA_TRAP, VITAL_SPIRIT, WHITE_SMOKE = 68, 69, 70, 71, 72, 73
PURE_POWER, SHELL_ARMOR, AIR_LOCK = 74, 75, 77

CLOSEST: dict[str, tuple[int, str]] = {
    "tangled-feet": (OWN_TEMPO, "confusion-related"),
    "motor-drive": (VOLT_ABSORB, "electric immunity"),
    "rivalry": (GUTS, "conditional damage boost"),
    "steadfast": (INNER_FOCUS, "flinch-related"),
    "snow-cloak": (SAND_VEIL, "weather evasion"),
    "gluttony": (PICKUP, "berry/item flavor"),
    "anger-point": (GUTS, "reacts to damage with attack"),
    "unburden": (CHLOROPHYLL, "conditional speed doubling"),
    "heatproof": (THICK_FAT, "halves fire damage"),
    "simple": (OWN_TEMPO, "no analog; neutral"),
    "dry-skin": (WATER_ABSORB, "water immunity, heals"),
    "download": (TRACE, "reads the foe on entry"),
    "iron-fist": (GUTS, "move-class damage boost"),
    "poison-heal": (GUTS, "benefits from poison"),
    "adaptability": (HUSTLE, "STAB-style damage boost"),
    "skill-link": (COMPOUND_EYES, "consistency of multi-hit"),
    "hydration": (SHED_SKIN, "status cure"),
    "solar-power": (CHLOROPHYLL, "sun-based boost"),
    "sniper": (COMPOUND_EYES, "crit/accuracy flavor"),
    "magic-guard": (SHIELD_DUST, "blocks side effects"),
    "no-guard": (COMPOUND_EYES, "accuracy"),
    "technician": (HUSTLE, "damage boost"),
    "leaf-guard": (NATURAL_CURE, "status protection"),
    "klutz": (OBLIVIOUS, "no analog; neutral, no encounter effect"),
    "mold-breaker": (HUSTLE, "aggressive"),
    "super-luck": (SERENE_GRACE, "luck/chance"),
    "aftermath": (ROUGH_SKIN, "punishes attackers"),
    "anticipation": (PRESSURE, "informational"),
    "forewarn": (PRESSURE, "informational"),
    "unaware": (OBLIVIOUS, "ignores stat changes"),
    "tinted-lens": (COMPOUND_EYES, "not-very-effective moves hit harder"),
    "filter": (THICK_FAT, "reduces damage"),
    "slow-start": (TRUANT, "slow"),
    "scrappy": (INNER_FOCUS, "no analog"),
    "storm-drain": (WATER_ABSORB, "water redirect/absorb"),
    "ice-body": (RAIN_DISH, "weather healing"),
    "solid-rock": (THICK_FAT, "reduces damage"),
    "snow-warning": (SAND_STREAM, "weather setter (no hail in Gen 3)"),
    "honey-gather": (PICKUP, "item pickup"),
    "frisk": (KEEN_EYE, "informational"),
    "reckless": (GUTS, "recoil-move boost"),
    "multitype": (PRESSURE, "legendary"),
    "flower-gift": (CHLOROPHYLL, "sun-based"),
    "bad-dreams": (INSOMNIA, "sleep-related"),
    "pickpocket": (STICKY_HOLD, "item theft"),
    "sheer-force": (HUSTLE, "damage boost"),
    "contrary": (CLEAR_BODY, "stat-change interplay"),
    "unnerve": (PRESSURE, "intimidating"),
    "defiant": (WHITE_SMOKE, "reacts to stat drops"),
    "defeatist": (OWN_TEMPO, "drawback; neutral"),
    "cursed-body": (EFFECT_SPORE, "contact-style effect"),
    "healer": (SHED_SKIN, "status cure"),
    "friend-guard": (SHELL_ARMOR, "damage protection"),
    "weak-armor": (STURDY, "durability"),
    "heavy-metal": (STURDY, "weight"),
    "light-metal": (OBLIVIOUS, "weight; neutral"),
    "flare-boost": (GUTS, "burn-based"),
    "harvest": (PICKUP, "berries"),
    "telepathy": (OBLIVIOUS, "no analog; neutral"),
    "moody": (SPEED_BOOST, "stat gains over time"),
    "overcoat": (SHIELD_DUST, "weather/powder protection"),
    "poison-touch": (POISON_POINT, "poison on contact"),
    "regenerator": (NATURAL_CURE, "heals on switch-out"),
    "big-pecks": (CLEAR_BODY, "defense protection"),
    "sand-rush": (SWIFT_SWIM, "weather speed"),
    "wonder-skin": (SHIELD_DUST, "status protection"),
    "analytic": (COMPOUND_EYES, "attack-order boost"),
    "illusion": (COLOR_CHANGE, "deception"),
    "infiltrator": (KEEN_EYE, "bypasses defenses"),
    "mummy": (ROUGH_SKIN, "contact effect"),
    "moxie": (GUTS, "attack boost"),
    "justified": (INNER_FOCUS, "reacts to dark moves"),
    "rattled": (RUN_AWAY, "skittish"),
    "magic-bounce": (CLEAR_BODY, "protection"),
    "sap-sipper": (WATER_ABSORB, "absorbs a type"),
    "prankster": (RUN_AWAY, "no analog; neutral"),
    "sand-force": (SAND_VEIL, "sandstorm"),
    "iron-barbs": (ROUGH_SKIN, "punishes contact"),
    "zen-mode": (OBLIVIOUS, "form change; neutral"),
    "victory-star": (COMPOUND_EYES, "accuracy"),
    "turboblaze": (PRESSURE, "legendary"),
    "teravolt": (PRESSURE, "legendary"),
    "aroma-veil": (OWN_TEMPO, "mental-move protection"),
    "flower-veil": (SHIELD_DUST, "protection"),
    "cheek-pouch": (PICKUP, "berries"),
    "protean": (COLOR_CHANGE, "type changing"),
    "fur-coat": (MARVEL_SCALE, "physical defense"),
    "magician": (PICKUP, "item stealing"),
    "bulletproof": (SOUNDPROOF, "move-class immunity"),
    "competitive": (WHITE_SMOKE, "reacts to stat drops"),
    "strong-jaw": (HUSTLE, "move-class boost"),
    "refrigerate": (HUSTLE, "type-changing boost"),
    "sweet-veil": (INSOMNIA, "sleep immunity"),
    "stance-change": (PRESSURE, "form change"),
    "gale-wings": (EARLY_BIRD, "speed/priority flavor"),
    "mega-launcher": (HUSTLE, "move-class boost"),
    "grass-pelt": (OVERGROW, "grass flavor"),
    "symbiosis": (PICKUP, "item sharing"),
    "tough-claws": (HUSTLE, "contact boost"),
    "pixilate": (HUSTLE, "type-changing boost"),
    "gooey": (STATIC, "contact slows the attacker"),
    "dark-aura": (PRESSURE, "legendary"),
    "fairy-aura": (PRESSURE, "legendary"),
    "aura-break": (PRESSURE, "legendary"),
    "stamina": (STURDY, "durability"),
    "wimp-out": (RUN_AWAY, "flees"),
    "emergency-exit": (RUN_AWAY, "flees"),
    "water-compaction": (STURDY, "defense up when hit"),
    "merciless": (POISON_POINT, "poison-related"),
    "shields-down": (SHELL_ARMOR, "shell"),
    "stakeout": (HUSTLE, "damage boost"),
    "water-bubble": (WATER_VEIL, "burn immunity, fire resist"),
    "steelworker": (HUSTLE, "type boost"),
    "berserk": (GUTS, "reacts to damage"),
    "slush-rush": (SWIFT_SWIM, "weather speed"),
    "long-reach": (KEEN_EYE, "no analog"),
    "liquid-voice": (SOUNDPROOF, "sound-related"),
    "triage": (SHED_SKIN, "healing"),
    "schooling": (SWIFT_SWIM, "water"),
    "disguise": (STURDY, "survives a hit"),
    "corrosion": (POISON_POINT, "poison-related"),
    "comatose": (INSOMNIA, "sleep/status immune"),
    "queenly-majesty": (INNER_FOCUS, "blocks priority"),
    "innards-out": (ROUGH_SKIN, "punishes attackers"),
    "dancer": (OWN_TEMPO, "no analog; neutral"),
    "battery": (PLUS, "ally special boost"),
    "fluffy": (THICK_FAT, "damage reduction"),
    "dazzling": (INNER_FOCUS, "blocks priority"),
    "soul-heart": (PRESSURE, "legendary"),
    "receiver": (TRACE, "copies an ally's ability"),
    "beast-boost": (PRESSURE, "ultra beast"),
    "rks-system": (PRESSURE, "legendary-class"),
    "electric-surge": (STATIC, "electric flavor"),
    "psychic-surge": (SYNCHRONIZE, "psychic flavor"),
    "misty-surge": (WATER_VEIL, "status protection"),
    "grassy-surge": (OVERGROW, "grass flavor"),
    "full-metal-body": (CLEAR_BODY, "stat protection"),
    "shadow-shield": (THICK_FAT, "damage reduction"),
    "prism-armor": (THICK_FAT, "damage reduction"),
    "intrepid-sword": (INTIMIDATE, "stat effect on entry"),
    "dauntless-shield": (CLEAR_BODY, "stat protection"),
    "libero": (COLOR_CHANGE, "type changing"),
    "ball-fetch": (PICKUP, "item pickup"),
    "cotton-down": (EFFECT_SPORE, "contact effect"),
    "propeller-tail": (LIGHTNING_ROD, "redirect immunity"),
    "mirror-armor": (CLEAR_BODY, "stat protection"),
    "gulp-missile": (TORRENT, "water"),
    "stalwart": (INNER_FOCUS, "no analog"),
    "steam-engine": (FLAME_BODY, "fire/steam"),
    "punk-rock": (SOUNDPROOF, "sound-related"),
    "sand-spit": (SAND_STREAM, "sets sandstorm"),
    "ice-scales": (THICK_FAT, "damage reduction"),
    "ripen": (PICKUP, "berries"),
    "ice-face": (STURDY, "survives a hit"),
    "power-spot": (PLUS, "ally boost"),
    "screen-cleaner": (OWN_TEMPO, "no analog; neutral"),
    "steely-spirit": (PLUS, "ally boost"),
    "perish-body": (SHADOW_TAG, "trapping"),
    "wandering-spirit": (ROUGH_SKIN, "contact effect"),
    "hunger-switch": (OWN_TEMPO, "form change; neutral"),
    "unseen-fist": (GUTS, "contact-move boost"),
    "transistor": (PLUS, "electric boost"),
    "dragons-maw": (GUTS, "type boost"),
    "chilling-neigh": (GUTS, "attack boost on KO"),
    "grim-neigh": (GUTS, "attack boost on KO"),
    "lingering-aroma": (EFFECT_SPORE, "contact effect"),
    "seed-sower": (OVERGROW, "grass flavor"),
    "thermal-exchange": (WATER_VEIL, "burn immunity"),
    "anger-shell": (GUTS, "reacts to damage"),
    "purifying-salt": (IMMUNITY, "status immunity"),
    "well-baked-body": (FLASH_FIRE, "fire immunity"),
    "wind-rider": (SOUNDPROOF, "wind-move immunity (analog)"),
    "guard-dog": (INNER_FOCUS, "no analog"),
    "rocky-payload": (ROCK_HEAD, "rock flavor"),
    "wind-power": (VOLT_ABSORB, "charges on wind"),
    "zero-to-hero": (TORRENT, "water"),
    "commander": (OWN_TEMPO, "no analog; neutral"),
    "electromorphosis": (VOLT_ABSORB, "charges when hit"),
    "protosynthesis": (PRESSURE, "paradox"),
    "quark-drive": (PRESSURE, "paradox"),
    "good-as-gold": (CLEAR_BODY, "status/stat protection"),
    "vessel-of-ruin": (INTIMIDATE, "lowers foe stats"),
    "sword-of-ruin": (INTIMIDATE, "lowers foe stats"),
    "tablets-of-ruin": (INTIMIDATE, "lowers foe stats"),
    "beads-of-ruin": (INTIMIDATE, "lowers foe stats"),
    "orichalcum-pulse": (DROUGHT, "sets sun"),
    "hadron-engine": (STATIC, "electric flavor"),
    "opportunist": (SYNCHRONIZE, "copies the foe"),
    "cud-chew": (PICKUP, "berries"),
    "sharpness": (GUTS, "move-class boost"),
    "supreme-overlord": (GUTS, "attack boost"),
    "costar": (TRACE, "copies an ally"),
    "toxic-debris": (ROUGH_SKIN, "punishes attackers"),
    "armor-tail": (INNER_FOCUS, "blocks priority"),
    "earth-eater": (WATER_ABSORB, "absorbs a type"),
    "mycelium-might": (OWN_TEMPO, "no analog; neutral"),
    "supersweet-syrup": (INTIMIDATE, "lowers foe stat"),
    "hospitality": (SHED_SKIN, "heals allies"),
    "toxic-chain": (POISON_POINT, "poison"),
    "tera-shift": (PRESSURE, "legendary"),
    "poison-puppeteer": (POISON_POINT, "poison"),
    # added with the alternate forms (tools/form_list.py)
    "gorilla-tactics": (GUTS, "attack boost with a drawback"),
    "mimicry": (COLOR_CHANGE, "changes type"),
    "as-one-glastrier": (PRESSURE, "Unnerve + Chilling Neigh; legendary"),
    "as-one-spectrier": (PRESSURE, "Unnerve + Grim Neigh; legendary"),
    "minds-eye": (KEEN_EYE, "ignores evasion / accuracy drops"),
    "power-construct": (PRESSURE, "legendary form change"),
}


def cart_id(pokeapi_id: int, slug: str) -> int | None:
    """The cart ability for a PokéAPI ability, or None when none is mapped."""
    if 1 <= pokeapi_id <= 75:
        return pokeapi_id
    if pokeapi_id == 76:        # Air Lock: the cart's id is 77 (76 is Cacophony)
        return AIR_LOCK
    hit = CLOSEST.get(slug)
    return hit[0] if hit else None
