#!/usr/bin/env python3
"""
Pack the cries for National Dex species #387-1025 into one file.

Input: a folder of one <STEM>.ogg per species/form (the Gen 9 pack's
Audio/SE/Cries). Output:
  assets/cries/cries.pak   every cry's Ogg bytes, back to back
  data/cries.lua           slot -> { offset, length } in that file

One file instead of 639: src/cry_art.lua reads cries.pak once and slices a
cry out when it plays. Ogg bytes are copied untouched. Output is
deterministic (species order, no timestamps).

A species' file is looked up as its sprite stem (--stems: data/dbk_data.lua's
`species` map, e.g. MIME_JR -> MIMEJR), then its own id, then the stem
without a form suffix (BASCULIN_2 -> BASCULIN). One with none is reported
and simply has no cry.

Usage:
    python tools/build_cries.py --cries <pack>/Audio/SE/Cries \
        --stems <g9-battle-sprites>/data/dbk_data.lua
"""

from __future__ import annotations

import argparse
import glob
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIRST_DEX, LAST_DEX = 387, 1025
SLOT_OFFSET = 64


def species_ids(payload: Path) -> list[tuple[int, str]]:
    recs = []
    for path in sorted(glob.glob(str(payload / "[0-9]*.lua"))):
        text = Path(path).read_text(encoding="utf-8")
        for block in re.split(r"\n  \{", text):
            i = re.search(r'\bid = "([^"]+)"', block)
            d = re.search(r"\bdex = (\d+)", block)
            if i and d and FIRST_DEX <= int(d.group(1)) <= LAST_DEX:
                recs.append((int(d.group(1)), i.group(1)))
    recs.sort()
    return recs


def stem_map(path: Path | None) -> dict[str, str]:
    if not path or not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    section = re.search(r"species\s*=\s*\{(.*?)\n  \}", text, re.S)
    return dict(re.findall(r'\["([^"]+)"\]\s*=\s*"([^"]+)"', section.group(1) if section else text))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cries", type=Path, required=True)
    ap.add_argument("--stems", type=Path, default=None)
    ap.add_argument("--payload", type=Path, default=ROOT / "data" / "species")
    ap.add_argument("--out", type=Path, default=ROOT)
    args = ap.parse_args()

    stems = stem_map(args.stems)
    have = {p.stem for p in args.cries.glob("*.ogg")}
    species = species_ids(args.payload)

    blob = bytearray()
    rows, missing = [], []
    for dex, sid in species:
        stem = stems.get(sid)
        candidates = [stem, sid, re.sub(r"_\d+$", "", stem) if stem else None]
        pick = next((c for c in candidates if c and c in have), None)
        if not pick:
            missing.append(sid)
            continue
        data = (args.cries / f"{pick}.ogg").read_bytes()
        rows.append((dex + SLOT_OFFSET, len(blob), len(data), sid))
        blob += data

    pak = args.out / "assets" / "cries" / "cries.pak"
    pak.parent.mkdir(parents=True, exist_ok=True)
    pak.write_bytes(bytes(blob))
    lines = [
        "-- Generated by tools/build_cries.py. Do not edit by hand; rerun the tool instead.",
        "-- species slot (dex + 64) -> { offset, length } of its Ogg in assets/cries/cries.pak.",
        "return {",
    ]
    lines += [f"  [{slot}] = {{ {off}, {ln} }}, -- {sid}" for slot, off, ln, sid in rows]
    lines += ["}", ""]
    (args.out / "data" / "cries.lua").write_text("\n".join(lines), encoding="utf-8")
    print(f"cries: {len(rows)}/{len(species)}, {len(blob)} bytes")
    if missing:
        print("no cry for: " + ", ".join(missing))


if __name__ == "__main__":
    main()
