#!/usr/bin/env python3
"""
Build national_dex_gen3's evolution-item payload and icon atlas.

Some of this mod's own evolutions (data/species/*.lua, data/species/crossgen.lua)
call for an item no Gen 3 game has (Dusk Stone, Protector, ...). Species.itemIndex
waits for ANY installed mod to provide one; this tool builds the one THIS mod now
provides itself: data/items.lua (what to register) and assets/items/icons.png +
data/item_icons.lua (their Bag icons, for games that have one).

ORDER below is append-only: an item's `index` is its position in that list, and
`index` is what the engine stores in saves (storage.items[i].id) and in
src/item_art.lua's UI hook. Reordering or removing an entry would change what a
previously-saved item turns into. Add new items at the end.

Icons come from the third-party pokesprite pack (not shipped; --icons points at
a local checkout). An item ORDER lists but the pack has no icon for keeps
working -- it just has no Bag icon (src/item_art.lua falls through to the
game's own, which draws nothing for an unknown id).

Usage:
    python tools/build_items.py --icons <pokesprite>/items
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
INDEX_BASE = 900   # first slot; comfortably above every Gen 3 game's own
                   # item ids (the highest this engine knows of is 365)
ICON_SIZE = 24     # the Bag's own icon slot, both FRLG's and RSE's bag_chrome

# Append-only. Slug: the PokeAPI/evolution-data id (data/species/*.lua `item`
# fields and data/species/crossgen.lua). Do not reorder, remove, or insert.
ORDER = [
    "dawn-stone", "dubious-disc", "dusk-stone", "electirizer", "ice-stone",
    "magmarizer", "protector", "reaper-cloth", "sachet", "shiny-stone",
    "sweet-apple", "tart-apple", "whipped-dream",
    # the Gen 9 items below: not in every "icones animados"/pokesprite
    # checkout; registered regardless (see ORDER's own docstring above)
    "auspicious-armor", "black-augurite", "malicious-armor", "metal-alloy",
    "peat-block", "syrupy-apple",
]


def engine_id(slug: str) -> str:
    return slug.upper().replace("-", "_")


def display_name(slug: str) -> str:
    return slug.replace("-", " ").title()


def find_icon(icons_root: Path, slug: str) -> Path | None:
    # pokesprite names files with hyphens; hand-added ones may use underscores
    for name in (slug, slug.replace("-", "_")):
        hit = sorted(icons_root.rglob(f"{name}.png"))
        if hit:
            return hit[0]
    return None


def write_items(path: Path) -> None:
    lines = [
        "-- Generated by tools/build_items.py. Do not edit by hand; rerun the",
        "-- tool instead (see tools/build_items.py's ORDER for why entries are",
        "-- append-only).",
        "--",
        "-- The evolution items no Gen 3 game has, that this mod's own evolutions",
        "-- (data/species, data/species/crossgen.lua) call for. src/items.lua",
        "-- registers each at its own fixed slot (index = 900 + position here).",
        "return {",
    ]
    for i, slug in enumerate(ORDER):
        lines.append(f'  {{ slug = "{slug}", id = "{engine_id(slug)}", '
                     f'name = "{display_name(slug)}", index = {INDEX_BASE + i} }},')
    lines += ["}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def build_icons(icons_root: Path | None, out_png: Path, out_lua: Path) -> None:
    found: dict[str, Path] = {}
    if icons_root and icons_root.is_dir():
        for slug in ORDER:
            hit = find_icon(icons_root, slug)
            if hit:
                found[slug] = hit
    missing = [s for s in ORDER if s not in found]

    cols = max(1, min(len(found), 16))
    rows = -(-max(1, len(found)) // cols)
    sheet = Image.new("RGBA", (cols * ICON_SIZE, rows * ICON_SIZE), (0, 0, 0, 0))
    cells: dict[int, tuple[int, int]] = {}
    for i, slug in enumerate(s for s in ORDER if s in found):
        with Image.open(found[slug]) as im:
            icon = im.convert("RGBA")
            if icon.size != (ICON_SIZE, ICON_SIZE):
                icon = icon.resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS)
        x, y = (i % cols) * ICON_SIZE, (i // cols) * ICON_SIZE
        sheet.paste(icon, (x, y))
        cells[ORDER.index(slug)] = (x, y)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(out_png, optimize=True, compress_level=9)

    lines = [
        "-- Generated by tools/build_items.py. Do not edit by hand; rerun the tool",
        "-- instead. index -> where its 24x24 icon sits in assets/items/icons.png,",
        "-- for whichever of this mod's items the icon pack had art for.",
        "return {",
        f"  size = {ICON_SIZE},",
        "  cells = {",
    ]
    for i, slug in enumerate(ORDER):
        if i in cells:
            x, y = cells[i]
            lines.append(f"    [{INDEX_BASE + i}] = {{ x = {x}, y = {y} }}, -- {slug}")
    lines += ["  },", "}", ""]
    out_lua.write_text("\n".join(lines), encoding="utf-8")

    print(f"items: {len(ORDER)}, icons: {len(found)}/{len(ORDER)}")
    if missing:
        print("no icon for: " + ", ".join(missing))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--icons", type=Path, default=None,
                    help="root of a local pokesprite-style item icon pack "
                         "(searched recursively for <slug>.png); omit to skip icons")
    ap.add_argument("--out", type=Path, default=ROOT)
    args = ap.parse_args()

    write_items(args.out / "data" / "items.lua")
    build_icons(args.icons, args.out / "assets" / "items" / "icons.png",
               args.out / "data" / "item_icons.lua")
    print("wrote", args.out / "data" / "items.lua")


if __name__ == "__main__":
    main()
