#!/usr/bin/env python3
"""
Build national_dex_gen3's evolution-item payload and icon atlas.

Some of this mod's own evolutions (data/species/*.lua, data/species/crossgen.lua)
call for an item no Gen 3 game has (Dusk Stone, Protector, ...). Species.itemIndex
waits for ANY installed mod to provide one; this tool builds the one THIS mod now
provides itself: data/items.lua (what to register) and assets/items/icons.png +
data/item_icons.lua (their Bag icons, for games that have one).

ORDER below is append-only: an item's `index` is its position in that list, and
`index` is what the engine stores in saves (storage.items[i].id) and in
src/item_art.lua's UI hook. Reordering or removing an entry would change what a
previously-saved item turns into. Add new items at the end.

Icons come from the third-party pokesprite pack (not shipped; --icons points at
a local checkout). An item ORDER lists but the pack has no icon for keeps
working -- it just has no Bag icon (src/item_art.lua falls through to the
game's own, which draws nothing for an unknown id).

Usage:
    python tools/build_items.py --icons <pokesprite>/items
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
INDEX_BASE = 900   # first slot; comfortably above every Gen 3 game's own
                   # item ids (the highest this engine knows of is 365)
ICON_SIZE = 24     # the Bag's own icon slot, both FRLG's and RSE's bag_chrome

# Append-only. Slug: the PokeAPI/evolution-data id (data/species/*.lua `item`
# fields and data/species/crossgen.lua). Do not reorder, remove, or insert.
ORDER = [
    "dawn-stone", "dubious-disc", "dusk-stone", "electirizer", "ice-stone",
    "magmarizer", "protector", "reaper-cloth", "sachet", "shiny-stone",
    "sweet-apple", "tart-apple", "whipped-dream",
    # the Gen 9 items below: not in every "icones animados"/pokesprite
    # checkout; registered regardless (see ORDER's own docstring above)
    "auspicious-armor", "black-augurite", "malicious-armor", "metal-alloy",
    "peat-block", "syrupy-apple",
    # Sinistea / Poltchageist: two items each (phony/antique, counterfeit/artisan)
    "cracked-pot", "chipped-pot", "unremarkable-teacup", "masterpiece-teacup",
    # Milcery -> Alcremie: any one of the seven sweets, held
    "strawberry-sweet", "berry-sweet", "love-sweet", "star-sweet", "clover-sweet",
    "flower-sweet", "ribbon-sweet",
    # held-item evolutions (Sneasel, Gligar, Happiny, Bisharp) and Kubfu's scrolls
    "razor-claw", "razor-fang", "oval-stone", "leaders-crest",
    "scroll-of-darkness", "scroll-of-waters",
]

# Items whose icon is not in the pokesprite folder (--icons) but in the Gen 9 Pack's
# Graphics/Items (--extra-icons, one 48x48 PNG per item, named without separators).
EXTRA_ICON_FILES = {"leaders-crest": "LEADERSCREST", "scroll-of-darkness": "SCROLLOFDARKNESS",
                    "scroll-of-waters": "SCROLLOFWATERS"}

# slug -> file stem when the pack spells the item differently (pokesprite
# calls the teacups "teapot")
ICON_ALIASES = {"unremarkable-teacup": "unremarkable-teapot",
                "masterpiece-teacup": "masterpiece-teapot"}


def engine_id(slug: str) -> str:
    return slug.upper().replace("-", "_")


NAME_OVERRIDES = {"leaders-crest": "Leader's Crest", "scroll-of-darkness": "Scroll of Darkness",
                  "scroll-of-waters": "Scroll of Waters"}


def display_name(slug: str) -> str:
    return NAME_OVERRIDES.get(slug) or slug.replace("-", " ").title()


def find_icon(icons_root: Path, slug: str) -> Path | None:
    # pokesprite names files with hyphens; hand-added ones may use underscores
    alias = ICON_ALIASES.get(slug, slug)
    for name in (slug, slug.replace("-", "_"), alias, alias.replace("-", "_")):
        hit = sorted(icons_root.rglob(f"{name}.png"))
        if hit:
            return hit[0]
    return None


DEFAULT_PRICE = 2100   # the classic Gen 3 evolution stone price, when the wiki has none


# Shop prices Bulbapedia lists directly as the buy price, where 2x the sell price would
# be wrong (the Chipped Pot sells for 19,000 but is bought for 3,000).
BUY_PRICES = {"cracked-pot": 3000, "chipped-pot": 3000}


def derive_price(slug: str, prices: dict) -> tuple[int, str]:
    """Shop buy price: twice the sell price of the earliest game that lists
    one (a shop buys at half what it sells for), from tools/item_prices.json
    (tools/fetch_item_prices.py, Bulbapedia). Returns (price, why)."""
    if slug in BUY_PRICES:
        return BUY_PRICES[slug], "Bulbapedia buy price"
    for row in (prices.get(slug) or {}).get("prices", []):
        if row.get("sell"):
            return row["sell"] * 2, "2x sell price %d (%s)" % (row["sell"], ",".join(row["games"]))
    return DEFAULT_PRICE, "no price data; classic stone price"


def write_items(path: Path, prices: dict) -> None:
    lines = [
        "-- Generated by tools/build_items.py. Do not edit by hand; rerun the",
        "-- tool instead (see tools/build_items.py's ORDER for why entries are",
        "-- append-only).",
        "--",
        "-- The evolution items no Gen 3 game has, that this mod's own evolutions",
        "-- (data/species, data/species/crossgen.lua) call for. src/items.lua",
        "-- registers each at its own fixed slot (index = 900 + position here). price is",
        "-- the shop price from tools/item_prices.json (Bulbapedia): 2x the earliest sell price.",
        "return {",
    ]
    for i, slug in enumerate(ORDER):
        price, why = derive_price(slug, prices)
        lines.append(f'  {{ slug = "{slug}", id = "{engine_id(slug)}", '
                     f'name = "{display_name(slug)}", index = {INDEX_BASE + i}, '
                     f'price = {price} }}, -- {why}')
    lines += ["}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def build_icons(icons_root: Path | None, out_png: Path, out_lua: Path,
                extra_root: Path | None = None) -> None:
    found: dict[str, Path] = {}
    if icons_root and icons_root.is_dir():
        for slug in ORDER:
            hit = find_icon(icons_root, slug)
            if hit:
                found[slug] = hit
    if extra_root and extra_root.is_dir():
        for slug, stem in EXTRA_ICON_FILES.items():
            path = extra_root / f"{stem}.png"
            if slug not in found and path.exists():
                found[slug] = path
    missing = [s for s in ORDER if s not in found]

    cols = max(1, min(len(found), 16))
    rows = -(-max(1, len(found)) // cols)
    sheet = Image.new("RGBA", (cols * ICON_SIZE, rows * ICON_SIZE), (0, 0, 0, 0))
    cells: dict[int, tuple[int, int]] = {}
    for i, slug in enumerate(s for s in ORDER if s in found):
        with Image.open(found[slug]) as im:
            icon = im.convert("RGBA")
            if icon.size != (ICON_SIZE, ICON_SIZE):
                icon = icon.resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS)
        x, y = (i % cols) * ICON_SIZE, (i // cols) * ICON_SIZE
        sheet.paste(icon, (x, y))
        cells[ORDER.index(slug)] = (x, y)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(out_png, optimize=True, compress_level=9)

    lines = [
        "-- Generated by tools/build_items.py. Do not edit by hand; rerun the tool",
        "-- instead. index -> where its 24x24 icon sits in assets/items/icons.png,",
        "-- for whichever of this mod's items the icon pack had art for.",
        "return {",
        f"  size = {ICON_SIZE},",
        "  cells = {",
    ]
    for i, slug in enumerate(ORDER):
        if i in cells:
            x, y = cells[i]
            lines.append(f"    [{INDEX_BASE + i}] = {{ x = {x}, y = {y} }}, -- {slug}")
    lines += ["  },", "}", ""]
    out_lua.write_text("\n".join(lines), encoding="utf-8")

    print(f"items: {len(ORDER)}, icons: {len(found)}/{len(ORDER)}")
    if missing:
        print("no icon for: " + ", ".join(missing))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--icons", type=Path, default=None,
                    help="root of a local pokesprite-style item icon pack "
                         "(searched recursively for <slug>.png); omit to skip icons")
    ap.add_argument("--extra-icons", type=Path, default=None,
                    help="the Gen 9 Pack's Graphics/Items folder, for the items the "
                         "pokesprite pack has no icon for (Leader's Crest, the scrolls)")
    ap.add_argument("--out", type=Path, default=ROOT)
    args = ap.parse_args()

    price_file = Path(__file__).resolve().parent / "item_prices.json"
    prices = json.loads(price_file.read_text(encoding="utf-8")) if price_file.exists() else {}
    write_items(args.out / "data" / "items.lua", prices)
    build_icons(args.icons, args.out / "assets" / "items" / "icons.png",
               args.out / "data" / "item_icons.lua", args.extra_icons)
    print("wrote", args.out / "data" / "items.lua")


if __name__ == "__main__":
    main()
